AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
Description: Fedex Final Project
Resources:
  # Dynamo table
  FedexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: fedex-table
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
    
  # Api gateway
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: fedex-api
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: fedex_swagger.yaml
            
  # SNS topic
  FedexTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Fedex-Corporation
      TopicName: Fedex-Topic
    
  #Lambda functions
  
  # Lambda function to change state to embarked of a package
  PutEmbarked:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fedexPutEmbarked
      Handler: task_03.fedexPutEmbarked
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FedexTable
        - DynamoDBReadPolicy:
            TableName: !Ref FedexTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FedexTopic.TopicName
        - SNSCrudPolicy:
            TopicName: !GetAtt FedexTopic.TopicName
      Environment:      
        Variables:
          FEDEX_TABLE: !Ref FedexTable
          TOPIC_ARN: !Ref FedexTopic
      Events:
        PutEmbarked:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/fedex/packages/{packageId}/embarked"
            Method: PUT
            
  # Lambda function to change state to routed of a package            
  PutRouted:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fedexPutRouted
      Handler: task_03.fedexPutRouted
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref FedexTable
        - DynamoDBReadPolicy:
            TableName: !Ref FedexTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt FedexTopic.TopicName
        - SNSCrudPolicy:
            TopicName: !GetAtt FedexTopic.TopicName
      Environment:
        Variables:
          FEDEX_TABLE: !Ref FedexTable
          TOPIC_ARN: !Ref FedexTopic
      Events:
        PutRouted:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/fedex/packages/{packageId}/routed"
            Method: PUT