openapi: 3.0.0

paths:
  /fedex/packages/{packageId}/embarked:
    put:
      summary: This endpoint changes the state of a package to embarked
      parameters:
        - name: packageId
          in: path
          required: true
          description: Package unique id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:fedexPutEmbarked/invocations"
        httpMethod: "POST"
        
  /fedex/packages/{packageId}/routed:
    put:
      summary: This endpoint changes the state of a package to routed
      parameters:
        - name: packageId
          in: path
          required: true
          description: Package unique id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:fedexPutRouted/invocations"
        httpMethod: "POST"