openapi: 3.0.0

paths:
  /packages/{packageId}:
    put:
      summary: This endpoint saves a package to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                last_name:
                  type: string
      parameters:
        - name: packageId
          in: path
          required: true
          description: Package unique id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putPackage/invocations"
        httpMethod: "POST"
        
  /fedex/packages/{packageId}/packaged:
    put:
      summary: This endpoint changes the state of a package to packaged
      parameters:
        - name: packageId
          in: path
          required: true
          description: Package unique id
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putPackaged/invocations"
        httpMethod: "POST"